name: Daily JSON Upload

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC) 실행
  workflow_dispatch:

jobs:
  upload-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run crawler and update data.json
        run: python upload.py

      - name: Commit and push
        run: |
          git config --global user.name 'Luka Bot'
          git config --global user.email 'lukabot@example.com'
          git add data.json
          git commit -m 'Auto-update data.json [LukaBot]' || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
